//int power (int a, int n){
 //4:     int r;
 //5:     r = a;
  power = e;
  *e++ = ENT; *e++ = 1;
  *e++ = LLA; *e++ = -1;
  *e++ = PSH;
  *e++ = LLA; *e++ = 3;
  *e++ = LI;
  *e++ = SI;
 //6:     if (n == 0) return 1;
  *e++ = LLA; *e++ = 2; 
  *e++ = LI;
  *e++ = PSH;
  *e++ = IMM; *e++ = 0;
  *e++ = EQ;
  *e++ = BZ; loc=e; *e++ = 0;
  *e++ = IMM; *e++ = 1;
  *e++ = LEV;
 //7:     while (n-1>0) {
  WhileBegin = e;  
  *loc = (int) e; *e++ = LLA; *e++ = 2;
  *e++ = LI;
  *e++ = PSH;
  *e++ = IMM; *e++ = 1;
  *e++ = SUB;
  *e++ = PSH;  
  *e++ = IMM; *e++ = 0;
  *e++ = GT;
  *e++ = BZ; loc=e; *e++ = 0;
 //8:         a = a*r;
  *e++ = LLA; *e++ = 3;
  *e++ = PSH;
  *e++ = LLA; *e++ = 3;
  *e++ = LI;
  *e++ = PSH;
  *e++ = LLA; *e++ = -1;
  *e++ = LI;
  *e++ = MUL;
  *e++ = SI;
 //9:         n = n-1;
  *e++ = LLA; *e++ = 2;
  *e++ = PSH;
  *e++ = LLA; *e++ = 2;
  *e++ = LI;
  *e++ = PSH;
  *e++ = IMM; *e++ = 1;
  *e++ = SUB;
  *e++ = SI;
 //10:     }
 //11:     return a;  
  *e++ = JMP; *e++ = WhileBegin;
  *loc = (int) e; *e++ = LLA; *e++ = 3;
  *e++ = LI;
  *e++ = LEV;
 //12: }
  *e++ = LEV;
 //13:
 //14: int main() {
 //15:     printf("power(2, 5)=%d\n", power(2, 5));
  pc = e;
  *e++ = ENT; *e++ = 0; 
  *e++ = IMM; *e++ = (int) "power(2, 5)=%d\n"; 
  *e++ = PSH;
  *e++ = IMM; *e++ = 2;
  *e++ = PSH;
  *e++ = IMM; *e++ = 5;
  *e++ = PSH;
  *e++ = JSR; *e++ = (int) power;
  *e++ = ADJ; *e++ = 2;
  *e++ = PSH;
  *e++ = PRTF;
  *e++ = ADJ; *e++ = 2;
  *e++ = LEV;
